### ISSUE TITLE
Add support for inserting same bookmark multiple times in Templates

### ISSUE THREAD

**Issue by akek** [AmmarZY/BBS#1]
Some of bookmarks in templates need to be duplicated within the document, Currently we can't use the value coming from system twice in template

**Comment by AmmarZY** [comment]
On business side, this enhancement requires valid real use case and customer need. on the implementation side, it requires more analysis, otherwise finding workaround is sufficient.

**Comment by AmmarZY** [comment]
I have added Cross Reference support to reference same bookmark multiple times. The following changes has been done:
1- Bookmarks has been recreated in the generated template to support cross reference.
2- Cross reference fields will be updated after updating the content of the bookmarks.

Please note that templates may need to be updated for this new change.
