### ISSUE TITLE
Separate page required for letter tracking

### ISSUE THREAD

**Issue by akek** [AmmarZY/BBS#8]
when tracking letter recipients, each time it takes long time to save, its better to separate creating templates each time you want to save tracking only.

**Comment by akek** [comment]
also, it's better to let it is behavior like event tracking and separate download link in new column

**Comment by AmmarZY** [comment]
I suggest to add an optional flag for the user [Process] in case he wants to regenerate the documents. The reason for the slowness is generating documents.
